### PR TITLE
Create utils module containing functions for creating requests

### PR DESCRIPTION
**Pull request by JiriPapousek**
# Description

Extract code related to sending HTTP requests from `content.go` and place it into separate module. This code will be later used in Service Log integration, so it would otherwise make duplicates.

## Type of change

- Refactor (refactoring code, removing useless files)

## Testing steps

Run locally, run unit tests.

## Checklist
* [x] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
Why not to use `utils` repository?

**Comment by JiriPapousek** [comment]
> Why not to use `utils` repository?

I went through the utils repo, just could not find these in there

**Comment by tisnik** [comment]
> > Why not to use `utils` repository?
> 
> I went through the utils repo, just could not find these in there

yup, put it there

**Review by tisnik — APPROVED** [review]
LGTM

**Review by juandspy — APPROVED** [review]

**Pull request merged**
